### ISSUE TITLE
Fatal error when deleting

### ISSUE THREAD

**Issue by BrianHenryIE** [helgatheviking/Radio-Buttons-for-Taxonomies#104]
<img width="707" alt="Screen Shot 2022-06-15 at 2 20 23 PM" src="https://user-images.githubusercontent.com/4720401/173932274-39b8bf49-0c18-4d8e-a19e-81ff7a5459f4.png">

```
PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method Radio_Buttons_For_Taxonomies::delete_plugin_options() cannot be called statically in /path/to/wp-includes/class-wp-hook.php:307
Stack trace:
#0 /path/to/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#1 /path/to/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#2 /path/to/wp-admin/includes/plugin.php(1265): do_action('uninstall_radio...')
#3 /path/to/wp-admin/includes/plugin.php(958): uninstall_plugin('radio-buttons-f...')
#4 /path/to/wp-admin/includes/ajax-actions.php(4668): delete_plugins(Array)
#5 /path/to/wp-includes/class-wp-hook.php(307): wp_ajax_delete_plugin('')
#6 /path/to/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#7 /path/to/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#8 /path/to/wp-admin/admin-ajax.php(187): do_action('wp_ajax_delete-...')
#9 {main}
  thrown in /path/to/wp-includes/class-wp-hook.php on line 307
```

Strange – I'm flushing clean two staging sites and had no problem on the other site.

PHP 8.

**Comment by helgatheviking** [comment]
Hi Brian. Looks like this [method](https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/blob/trunk/radio-buttons-for-taxonomies.php#L152) needs to be declared as static.

Otherwise, is it still all working with WP 6.0? Maybe I can bump the tested version at the same time.

**Comment by helgatheviking** [comment]
@BrianHenryIE let me know if that _didn't_ fix the problem. thanks for reporting!
