### ISSUE TITLE
Fatal error on version 2.0.0 + Wordpress 4.9 

### ISSUE THREAD

**Issue by cirofeitosa** [helgatheviking/Radio-Buttons-for-Taxonomies#61]
Since the latest update (version 2.0.0) we are receiving this fatal error:

`PHP Fatal error:  Uncaught Error: Call to undefined function use_block_editor_for_post_type() in /var/www/html/wp-content/plugins/radio-buttons-for-taxonomies/inc/class.WordPress_Radio_Taxonomy.php:82`
`Stack trace:`
`#0 /var/www/html/wp-includes/class-wp-hook.php(286): WordPress_Radio_Taxonomy->remove_meta_box('')`
`#1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)`
`#2 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)`
`#3 /var/www/html/wp-admin/includes/menu.php(149): do_action('admin_menu', '')`
`#4 /var/www/html/wp-admin/menu.php(294): require_once('/var/www/html/...')`
`#5 /var/www/html/wp-admin/admin.php(140): require('/var/www/html/...')`
`#6 /var/www/html/wp-admin/post.php(12): require_once('/var/www/html/...')`
`#7 {main}`
`thrown in /var/www/html/wp-content/plugins/radio-buttons-for-taxonomies/inc/class.WordPress_Radio_Taxonomy.php on...'`

We had to disable the plugin to reactivate the site.

Our Server stack:
- Apache 2.4.38
- PHP 7.3.4
- Wordpress 4.9

**Comment by cirofeitosa** [comment]
Was fixed on 2.0.1 version.
